### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by Kludex** [Kludex/awesome-pydantic#27]
If you want to help, drop a message. I need it. :)

**Comment by ischaojie** [comment]
Hi, I want to help if possible. :)

**Comment by Kludex** [comment]
It is. Thanks for volunteering. :pray:

My handler on Discord is Kludex#2710. If you can connect there, it will be really cool, so you can chat about it. :pray:

**Comment by ischaojie** [comment]
Hi, I have sent a friend request in Discord(chaojie#1984). I look forward to communicating with you.

**Comment by Kludex** [comment]
Closing this issue as @ischaojie is helping the project now. 🙏

Thanks @ischaojie! 🥳
