### ISSUE TITLE
Is the `awesome` action in the `.github` folder licensed under the same license as the `awesome-pydantic`?

### ISSUE THREAD

**Issue by hasansezertasan** [Kludex/awesome-pydantic#63]
Is the `awesome` action in the `.github` folder licensed under the same license as the `awesome-pydantic` and can I copy, modify, and use it in one of my projects ([awesome-python-html](https://github.com/hasansezertasan/awesome-python-html/))?

**Comment by Kludex** [comment]
Yes. 👍

**Comment by hasansezertasan** [comment]
> Yes. 👍

Thank you for the great work :rocket:.
